name: flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  awesome_dialog: ^3.2.1
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.5
  shared_preferences: ^2.3.2
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  file_picker: ^8.1.3
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/arroz.jpeg
    - assets/icons/icon1.png
    - assets/icons/icon2.png
    
    


